name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "https://fake.com"
  CLERK_SECRET_KEY: "https://fake.com",
  UPSTASH_REDIS_REST_URL: "https://fake.com",
  UPSTASH_REDIS_REST_TOKEN: "https://fake.com",

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name Install Dependencies        
      run: pnpm install

    - name Typecheck
      run: pnpm run typecheck

    - name Lint
    - run: pnpm run lint